---
title: Solid-state Batteries
author:
  - name: W. Chen
    corresponding: true
    email: chenweihengtz@nbut.edu.cn
    affiliations:
      - ref: affiliation1
      - ref: affiliation2
affiliations:
  - id: affiliation1
    name: Ningbo University of Technology
    department: Department of Mechanical Engineering
    city: Ningbo
    country: P. R. China
    postal_code: 315336
  - id: affiliation2
    name: Zhejiang Sci-Tech University
    department: Department of Mechanical Engineering
    city: Hangzhou
    country: P. R. China
    postal_code: 310018
date: last-modified
bibliography: references.bib
jupyter: python3
csl: /Users/chenn/Documents/Zotero.nosync/styles/elsevier-with-titles.csl
---

# Abstract {.unnumbered .unlisted}

<!-- 不编号也不在toc中显示，只有不编号的才能不显示 -->

# Title

In September 2021, a significant jump in seismic activity on the island of La Palma (Canary Islands, Spain) signaled the start of a volcanic crisis that still continues at the time of writing. Earthquake data is continually collected and published by the Instituto Geográphico Nacional (IGN). ...

## Introduction

```{python}
import matplotlib.pyplot as plt
import numpy as np
eruptions = [1492, 1585, 1646, 1677, 1712, 1949, 1971, 2021]
```

```{python}
#| label: fig-timeline
#| fig-cap: Timeline of recent earthquakes on La Palma
#| fig-alt: An event plot of the years of the last 8 eruptions on La Palma.

plt.figure(figsize=(6, 1))
plt.eventplot(eruptions, lineoffsets=0, linelengths=0.1, color='black')
plt.gca().axes.get_yaxis().set_visible(False)
plt.ylabel('')
plt.show()
```

```{python}
#| output: false

avg_years_between_eruptions = np.mean(np.diff(eruptions[:-1]))
avg_years_between_eruptions
```

Based on data up to and including 1971, eruptions on La Palma happen every 79.8 years on average. Studies of the magma systems feeding the volcano, such as [@albertus2021], have proposed that there are two main magma reservoirs feeding the Cumbre Vieja volcano; one in the mantle (30-40km depth) which charges and in turn feeds a shallower crustal reservoir (10-20km depth). Eight eruptions have been recorded since the late 1400s (@fig-timeline). Data and methods are discussed in @sec-data-methods. Let $x$ denote the number of eruptions in a year. Then, $x$ can be modeled by a Poisson distribution

$$
p(x) = \frac{e^{-\lambda} \lambda^{x}}{x !}
$$ {#eq-poisson}

where $\lambda$ is the rate of eruptions per year. Using @eq-poisson, the probability of an eruption in the next $t$ years can be calculated.

| Name                | Year |
|---------------------|------|
| Current             | 2021 |
| Teneguía            | 1971 |
| Nambroque           | 1949 |
| El Charco           | 1712 |
| Volcán San Antonio  | 1677 |
| Volcán San Martin   | 1646 |
| Tajuya near El Paso | 1585 |
| Montaña Quemada     | 1492 |

: Recent historic eruptions on La Palma {#tbl-history}

@tbl-history summarises the eruptions recorded since the colonization of the islands by Europeans in the late 1400s.




{{< embed notebooks/data-screening.qmd#fig-spatial-plot >}}

@fig-spatial-plot shows the location of recent Earthquakes on La Palma.

## Methods

## Results and Discussion {#sec-data-methods}

## Conclusion

## References {.unnumbered}

::: {#refs}
:::